[2022-10-28T18:28:55.771+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v0.calculate_hourly_demand_forecast manual__2022-10-28T18:28:38.620961+00:00 [queued]>
[2022-10-28T18:28:55.839+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v0.calculate_hourly_demand_forecast manual__2022-10-28T18:28:38.620961+00:00 [queued]>
[2022-10-28T18:28:55.839+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T18:28:55.840+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-28T18:28:55.840+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T18:28:55.904+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): calculate_hourly_demand_forecast> on 2022-10-28 18:28:38.620961+00:00
[2022-10-28T18:28:55.913+0000] {standard_task_runner.py:55} INFO - Started process 2900 to run task
[2022-10-28T18:28:55.930+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ENG_hourly_process_v0', 'calculate_hourly_demand_forecast', 'manual__2022-10-28T18:28:38.620961+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/ENG_hourly_process_dag.py', '--cfg-path', '/tmp/tmp32y_iw9o']
[2022-10-28T18:28:55.946+0000] {standard_task_runner.py:83} INFO - Job 68: Subtask calculate_hourly_demand_forecast
[2022-10-28T18:28:56.183+0000] {task_command.py:376} INFO - Running <TaskInstance: ENG_hourly_process_v0.calculate_hourly_demand_forecast manual__2022-10-28T18:28:38.620961+00:00 [running]> on host f011703e6eb5
[2022-10-28T18:28:56.432+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=colmo786@gmail.com
AIRFLOW_CTX_DAG_OWNER=energy
AIRFLOW_CTX_DAG_ID=ENG_hourly_process_v0
AIRFLOW_CTX_TASK_ID=calculate_hourly_demand_forecast
AIRFLOW_CTX_EXECUTION_DATE=2022-10-28T18:28:38.620961+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-28T18:28:38.620961+00:00
[2022-10-28T18:28:56.466+0000] {logging_mixin.py:120} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:297 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-10-28T18:28:56.468+0000] {logging_mixin.py:120} INFO - INFO calculate_hourly_demand_forecast execution init:  2022-10-28T18:28:38.620961+00:00
[2022-10-28T18:28:56.492+0000] {logging_mixin.py:120} INFO - INFO Module build_postgres_cnxn: DB Connection to host local_pgdb Ok
[2022-10-28T18:28:56.504+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ENG_hourly_process_dag.py", line 63, in calculate_hourly_demand_forecast
    , port=port, n_lookback=48, n_forecast=24, verbose=True)
  File "/opt/airflow/dags/energy.py", line 201, in _calculate_hourly_demand_forecast
    process_ok, error_txt, df_last_time = pg_select_to_pandas(cursor, sql_query, verbose=True)
TypeError: pg_select_to_pandas() got an unexpected keyword argument 'verbose'
[2022-10-28T18:28:56.520+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=ENG_hourly_process_v0, task_id=calculate_hourly_demand_forecast, execution_date=20221028T182838, start_date=20221028T182855, end_date=20221028T182856
[2022-10-28T18:28:56.568+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 68 for task calculate_hourly_demand_forecast (pg_select_to_pandas() got an unexpected keyword argument 'verbose'; 2900)
[2022-10-28T18:28:56.611+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-28T18:28:56.698+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
