[2022-10-26T19:50:01.061+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: get_hourly_demand_v1.get_hourly_demand manual__2022-10-26T19:48:52.930082+00:00 [queued]>
[2022-10-26T19:50:01.076+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: get_hourly_demand_v1.get_hourly_demand manual__2022-10-26T19:48:52.930082+00:00 [queued]>
[2022-10-26T19:50:01.076+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-26T19:50:01.076+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-10-26T19:50:01.076+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-26T19:50:01.096+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_hourly_demand> on 2022-10-26 19:48:52.930082+00:00
[2022-10-26T19:50:01.104+0000] {standard_task_runner.py:55} INFO - Started process 430 to run task
[2022-10-26T19:50:01.108+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_hourly_demand_v1', 'get_hourly_demand', 'manual__2022-10-26T19:48:52.930082+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/hourly_demand_dag.py', '--cfg-path', '/tmp/tmph9vrnfwn']
[2022-10-26T19:50:01.111+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask get_hourly_demand
[2022-10-26T19:50:01.205+0000] {task_command.py:376} INFO - Running <TaskInstance: get_hourly_demand_v1.get_hourly_demand manual__2022-10-26T19:48:52.930082+00:00 [running]> on host e08a6f070669
[2022-10-26T19:50:01.399+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=colmo786@gmail.com
AIRFLOW_CTX_DAG_OWNER=energy
AIRFLOW_CTX_DAG_ID=get_hourly_demand_v1
AIRFLOW_CTX_TASK_ID=get_hourly_demand
AIRFLOW_CTX_EXECUTION_DATE=2022-10-26T19:48:52.930082+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-26T19:48:52.930082+00:00
[2022-10-26T19:50:01.425+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/hourly_demand_dag.py", line 44, in get_hourly_demand
    database = Variable.get("ENERGY_DB")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable ENERGY_DB does not exist'
[2022-10-26T19:50:01.443+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=get_hourly_demand_v1, task_id=get_hourly_demand, execution_date=20221026T194852, start_date=20221026T195001, end_date=20221026T195001
[2022-10-26T19:50:01.472+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task get_hourly_demand ('Variable ENERGY_DB does not exist'; 430)
[2022-10-26T19:50:01.529+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-26T19:50:01.575+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
