[2022-10-28T22:39:26.186+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T22:05:00+00:00 [queued]>
[2022-10-28T22:39:26.225+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T22:05:00+00:00 [queued]>
[2022-10-28T22:39:26.228+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T22:39:26.228+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-28T22:39:26.228+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T22:39:26.316+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): calculate_hourly_demand_forecast> on 2022-10-26 22:05:00+00:00
[2022-10-28T22:39:26.342+0000] {standard_task_runner.py:55} INFO - Started process 1123 to run task
[2022-10-28T22:39:26.345+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ENG_hourly_process_v1', 'calculate_hourly_demand_forecast', 'scheduled__2022-10-26T22:05:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/ENG_hourly_process_dag.py', '--cfg-path', '/tmp/tmpwx7ypeyp']
[2022-10-28T22:39:26.347+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask calculate_hourly_demand_forecast
[2022-10-28T22:39:26.743+0000] {task_command.py:376} INFO - Running <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T22:05:00+00:00 [running]> on host 74ce152bc4b9
[2022-10-28T22:39:27.072+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=colmo786@gmail.com
AIRFLOW_CTX_DAG_OWNER=energy
AIRFLOW_CTX_DAG_ID=ENG_hourly_process_v1
AIRFLOW_CTX_TASK_ID=calculate_hourly_demand_forecast
AIRFLOW_CTX_EXECUTION_DATE=2022-10-26T22:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-26T22:05:00+00:00
[2022-10-28T22:39:27.088+0000] {logging_mixin.py:120} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:297 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-10-28T22:39:27.089+0000] {logging_mixin.py:120} INFO - INFO calculate_hourly_demand_forecast execution init:  2022-10-26T22:05:00+00:00
[2022-10-28T22:39:27.089+0000] {logging_mixin.py:120} INFO - WORKDIR: /opt/***
[2022-10-28T22:39:27.125+0000] {logging_mixin.py:120} INFO - INFO Module build_postgres_cnxn: DB Connection to host local_pgdb Ok
[2022-10-28T22:39:27.130+0000] {logging_mixin.py:120} INFO - INFO pg_select_to_pandas: query executed Ok. Number of records returned: 1
[2022-10-28T22:39:27.136+0000] {logging_mixin.py:120} INFO - INFO pg_select_to_pandas: query executed Ok. Number of records returned: 48
[2022-10-28T22:40:26.303+0000] {local_task_job.py:87} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-28T22:40:26.438+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 1123. PIDs of all processes in the group: [1123]
[2022-10-28T22:40:26.439+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 1123
[2022-10-28T22:40:26.962+0000] {taskinstance.py:1562} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-28T22:40:27.057+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ENG_hourly_process_dag.py", line 63, in calculate_hourly_demand_forecast
    , port=port, n_lookback=48, n_forecast=24, verbose=True)
  File "/opt/airflow/dags/energy.py", line 237, in _calculate_hourly_demand_forecast
    Y_ = model.predict(X_).reshape(-1, 1)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1564, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-10-28T22:40:27.125+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=ENG_hourly_process_v1, task_id=calculate_hourly_demand_forecast, execution_date=20221026T220500, start_date=20221028T223926, end_date=20221028T224027
[2022-10-28T22:40:27.289+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task calculate_hourly_demand_forecast (Task received SIGTERM signal; 1123)
[2022-10-28T22:40:27.861+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1123, status='terminated', exitcode=1, started='22:39:25') (1123) terminated with exit code 1
[2022-10-28T22:40:27.865+0000] {local_task_job.py:164} INFO - Task exited with return code 143
[2022-10-28T22:40:28.057+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
